kind: Deployment
apiVersion: apps/v1
metadata:
  name: ce-test
  labels:
    app: ce-test
    app.kubernetes.io/name: ce-test
    app.kubernetes.io/instance: ce-test
    app.kubernetes.io/component: ce-test
    app.kubernetes.io/part-of: ce-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ce-test
  template:
    metadata:
      labels:
        app: ce-test
    spec:
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 50Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          name: ce-test
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          image: 'docker.io/kbaig/ce-test:latest'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ce-test
  labels:
    app: ce-test
    app.kubernetes.io/name: ce-test
    app.kubernetes.io/instance: ce-test
    app.kubernetes.io/component: ce-test
    app.kubernetes.io/part-of: ce-test
spec:
  ports:
  - name: http-listener
    port: 8080
  selector:
    app: ce-test
