kind: Deployment
apiVersion: apps/v1
metadata:
  name: ce-test
  labels:
    app: ce-test
    app.kubernetes.io/name: ce-test
    app.kubernetes.io/instance: ce-test
    app.kubernetes.io/component: ce-test
    app.kubernetes.io/part-of: ce-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ce-test
  template:
    metadata:
      labels:
        app: ce-test
    spec:
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 50Mi
          name: ce-test
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          image: docker.io/kbaig/ce-test@sha256:60820f82aaabeb32c137650391fde6f27bd78825c6823b693bb851ab294e6888
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ce-test
  labels:
    app: ce-test
    app.kubernetes.io/name: ce-test
    app.kubernetes.io/instance: ce-test
    app.kubernetes.io/component: ce-test
    app.kubernetes.io/part-of: ce-test
spec:
  ports:
  - name: http-listener
    port: 8080
  selector:
    app: ce-test
